import type { Doctor } from "./types";

const rawDoctorsData: Omit<Doctor, "slug">[] = [
  {
    id: 1,
    name: "Dr. Sarah Chen",
    specialty: "Cardiology",
    department: "Cardiology",
    experience: "15+ years",
    rating: 4.9,
    education: "Harvard Medical School",
    bio: "Board-certified cardiologist specializing in interventional cardiology and heart failure management.",
    fullBio: "Dr. Sarah Chen is a renowned cardiologist with over 15 years of experience in diagnosing and treating complex cardiovascular conditions...",
    awards: ["Best Cardiologist Award 2024", "Excellence in Patient Care 2023", "Research Innovation Award 2022"],
    languages: ["English", "Mandarin"],
    availability: "Mon, Wed, Fri: 9AM - 5PM",
    image: "/doctors/doctor-1.jpg",
    gender: "female"
  },
  {
    id: 2,
    name: "Dr. Michael Roberts",
    specialty: "Neurology",
    department: "Internal Medicine",
    experience: "12+ years",
    rating: 4.8,
    education: "Johns Hopkins University",
    bio: "Expert in neurological disorders including stroke, epilepsy, and movement disorders.",
    fullBio: "Dr. Michael Roberts is a board-certified neurologist specializing in stroke care...",
    awards: ["Neurologist of the Year 2023", "Patient Choice Award 2022"],
    languages: ["English", "Spanish"],
    availability: "Tue, Thu: 10AM - 6PM",
    image: "/doctors/doctor-2.jpg",
    gender: "male"
  },
  {
    id: 3,
    name: "Dr. Emily Watson",
    specialty: "Pediatrics",
    department: "Pediatrics",
    experience: "10+ years",
    rating: 4.9,
    education: "Stanford University",
    bio: "Dedicated pediatrician with expertise in child development and pediatric infectious diseases.",
    fullBio: "Dr. Emily Watson is a compassionate pediatrician dedicated to providing exceptional care for children...",
    awards: ["Top Pediatrician 2024", "Community Care Excellence 2023"],
    languages: ["English"],
    availability: "Mon - Fri: 8AM - 4PM",
    image: "/doctors/doctor-3.jpg",
    gender: "female"
  },
  {
    id: 4,
    name: "Dr. James Miller",
    specialty: "Orthopedic Surgery",
    department: "Rehabilitation",
    experience: "18+ years",
    rating: 4.7,
    education: "Yale School of Medicine",
    bio: "Renowned orthopedic surgeon specializing in joint replacement and sports medicine.",
    fullBio: "Dr. James Miller is a highly skilled orthopedic surgeon with 18 years of experience...",
    awards: ["Excellence in Orthopedic Surgery 2024", "Innovation in Joint Replacement 2023"],
    languages: ["English", "French"],
    availability: "Mon, Wed, Thu: 9AM - 5PM",
    image: "/doctors/doctor-4.jpg",
    gender: "male"
  },
  {
    id: 5,
    name: "Dr. Maria Garcia",
    specialty: "Emergency Medicine",
    department: "Emergency",
    experience: "14+ years",
    rating: 4.8,
    education: "UCLA Medical School",
    bio: "Emergency medicine specialist with extensive trauma care experience.",
    fullBio: "Dr. Maria Garcia is a board-certified emergency medicine physician with 14 years of experience...",
    awards: ["Emergency Physician of the Year 2024", "Trauma Care Excellence 2023"],
    languages: ["English", "Spanish", "Portuguese"],
    availability: "Rotating shifts - 24/7 Emergency Coverage",
    gender: "female"
  },
  {
    id: 6,
    name: "Dr. David Kim",
    specialty: "Radiology",
    department: "Radiology",
    experience: "11+ years",
    rating: 4.6,
    education: "Columbia University",
    bio: "Diagnostic radiologist with expertise in MRI and CT imaging interpretation.",
    fullBio: "Dr. David Kim is an expert diagnostic radiologist with 11 years of experience in medical imaging.",
    awards: ["Excellence in Diagnostic Imaging 2023", "Research Achievement Award 2022"],
    languages: ["English", "Korean"],
    availability: "Mon - Fri: 7AM - 3PM",
    gender: "male"
  },
  {
    id: 7,
    name: "Dr. Jennifer Lee",
    specialty: "Internal Medicine",
    department: "Internal Medicine",
    experience: "9+ years",
    rating: 4.8,
    education: "University of Pennsylvania",
    bio: "Internal medicine physician focused on preventive care and chronic disease management.",
    fullBio: "Dr. Jennifer Lee is a dedicated internal medicine physician with 9 years of experience in adult primary care.",
    awards: ["Patient Satisfaction Award 2024", "Primary Care Excellence 2023"],
    languages: ["English", "Cantonese"],
    availability: "Mon, Tue, Thu, Fri: 9AM - 5PM",
    gender: "female"
  },
  {
    id: 8,
    name: "Dr. Robert Thompson",
    specialty: "Laboratory Medicine",
    department: "Laboratory",
    experience: "16+ years",
    rating: 4.7,
    education: "Duke University",
    bio: "Clinical pathologist ensuring accurate diagnostic testing and quality assurance.",
    fullBio: "Dr. Robert Thompson is a board-certified clinical pathologist with 16 years of experience...",
    awards: ["Laboratory Excellence Award 2024", "Quality Assurance Achievement 2023"],
    languages: ["English"],
    availability: "Mon - Fri: 8AM - 4PM",
    gender: "male"
  },
  {
    id: 9,
    name: "Dr. Deborah Florendo Acantilado",
    specialty: "Anesthesiology",
    department: "Surgery",
    experience: "",
    rating: 0,
    education: "",
    bio: "Anesthesiology specialist.",
    availability: "Schedule not available",
    image: "/doctors/1130796_OQ6UTW0-280x280.jpg",
    gender: "female"
  },
  {
    id: 10,
    name: "Dr. Romil Aguirre",
    specialty: "Pathology",
    department: "Laboratory",
    experience: "",
    rating: 0,
    education: "",
    bio: "Pathology specialist.",
    availability: "Schedule not available",
    image: "/doctors/1130796_OQ6UTW0-280x280.jpg",
    gender: "male"
  },
  {
    id: 11,
    name: "Dr. Emilia Alberto",
    specialty: "Pediatrics",
    department: "Pediatrics",
    experience: "",
    rating: 0,
    education: "",
    bio: "Pediatrics specialist.",
    availability: "Sat: 09:00-11:00AM",
    image: "/doctors/doctor-280x281.png",
    gender: "female"
  },
  {
    id: 12,
    name: "Dr. Karen Lazaro",
    specialty: "Endocrinology",
    department: "Internal Medicine",
    experience: "",
    rating: 0,
    education: "",
    bio: "Endocrinology specialist.",
    availability: "Mon, Wed, Fri: 2:00PM - 4:00PM",
    image: "/doctors/doctor-280x281.png",
    gender: "female"
  },
  {
    id: 13,
    name: "Dr. Arcy James Alejandre",
    specialty: "Gastroenterology",
    department: "Internal Medicine",
    experience: "",
    rating: 0,
    education: "",
    bio: "Gastroenterology specialist.",
    availability: "Mon, Wed, Fri: 10:00AM - 12:00NN",
    image: "/doctors/1130796_OQ6UTW0-280x280.jpg",
    gender: "male"
  },
  {
    id: 14,
    name: "Dr. Jay Alejandre",
    specialty: "Thoracic & Cardiovascular Surgery",
    department: "Surgery",
    experience: "",
    rating: 0,
    education: "",
    bio: "Thoracic & Cardiovascular Surgery specialist.",
    availability: "Schedule not available",
    image: "/doctors/1130796_OQ6UTW0-280x280.jpg",
    gender: "male"
  },
  {
    id: 15,
    name: "Dr. Marites Palma Alferez",
    specialty: "OB-Gynecology",
    department: "OB-Gynecology",
    experience: "",
    rating: 0,
    education: "",
    bio: "OB-Gynecology specialist.",
    availability: "Schedule not available",
    image: "/doctors/MG_0065-280x292.jpg",
    gender: "female"
  },
  {
    id: 16,
    name: "Dr. Tejane Calavera Andres",
    specialty: "Anesthesiology",
    department: "Surgery",
    experience: "",
    rating: 0,
    education: "",
    bio: "Anesthesiology specialist.",
    availability: "Schedule not available",
    image: "/doctors/1130796_OQ6UTW0-280x280.jpg",
    gender: "female"
  },
  {
    id: 17,
    name: "Dr. Argyll Arcigal",
    specialty: "Pediatrics",
    department: "Pediatrics",
    experience: "",
    rating: 0,
    education: "",
    bio: "Pediatrics specialist.",
    availability: "Schedule not available",
    image: "/doctors/1130796_OQ6UTW0-280x280.jpg",
    gender: "male"
  },
  {
    id: 18,
    name: "Dr. Susana Arcigal",
    specialty: "Dermatology",
    department: "Dermatology",
    experience: "",
    rating: 0,
    education: "",
    bio: "Dermatology specialist.",
    availability: "Schedule not available",
    image: "/doctors/doctor-280x281.png",
    gender: "female"
  },
  {
    id: 19,
    name: "Dr. Darwin Balasta",
    specialty: "Internal Medicine",
    department: "Internal Medicine",
    experience: "",
    rating: 0,
    education: "",
    bio: "Internal Medicine specialist.",
    availability: "Schedule not available",
    image: "/doctors/1130796_OQ6UTW0-280x280.jpg",
    gender: "male"
  },
  {
    id: 20,
    name: "Dr. Martin Louie Bangcoy",
    specialty: "Orthopedic Surgery",
    department: "Rehabilitation",
    experience: "",
    rating: 0,
    education: "",
    bio: "Orthopedic Surgery specialist.",
    availability: "Mon, Wed, Fri: 2:00PM - 4:00PM",
    image: "/doctors/MG_0049-280x280.jpg",
    gender: "male"
  },
  {
    id: 21,
    name: "Dr. Arthur Cliff Bayani",
    specialty: "Cardiology",
    department: "Cardiology",
    experience: "",
    rating: 0,
    education: "",
    bio: "Cardiology specialist.",
    availability: "Fri: 11:00AM - 12:00NN",
    image: "/doctors/1130796_OQ6UTW0-280x280.jpg",
    gender: "male"
  },
  {
    id: 22,
    name: "Dr. Margaret Bendebel",
    specialty: "Oncology",
    department: "Oncology",
    experience: "",
    rating: 0,
    education: "",
    bio: "Oncology specialist.",
    availability: "Mon, Wed, Fri: 2:00PM - 4:00PM",
    image: "/doctors/doctor-280x281.png",
    gender: "female"
  },
  {
    id: 23,
    name: "Dr. Ma. Janet Bobiles",
    specialty: "OB-Gynecology",
    department: "OB-Gynecology",
    experience: "",
    rating: 0,
    education: "",
    bio: "OB-Gynecology specialist.",
    availability: "Schedule not available",
    image: "/doctors/doctor-280x281.png",
    gender: "female"
  },
  {
    id: 24,
    name: "Dr. Jovencio Braga",
    specialty: "Radiology",
    department: "Radiology",
    experience: "",
    rating: 0,
    education: "",
    bio: "Radiology specialist.",
    availability: "Schedule not available",
    image: "/doctors/1130796_OQ6UTW0-280x280.jpg",
    gender: "male"
  },
  {
    id: 25,
    name: "Dr. Marvin Jay Bunquin",
    specialty: "Anesthesiology",
    department: "Surgery",
    experience: "",
    rating: 0,
    education: "",
    bio: "Anesthesiology specialist.",
    availability: "Schedule not available",
    image: "/doctors/MG_0052-280x267.jpg",
    gender: "male"
  },
  {
    id: 26,
    name: "Dr. Marie Grace Cal",
    specialty: "Pulmonology",
    department: "Internal Medicine",
    experience: "",
    rating: 0,
    education: "",
    bio: "Pulmonology specialist.",
    availability: "Tue, Thu, Sat: 11:00AM - 1:00PM",
    image: "/doctors/PhotoRoom-20230331-144948-e1717140808660-280x263.jpg",
    gender: "female"
  },
  {
    id: 27,
    name: "Dr. Adora Brigette Canlas",
    specialty: "OB-Gynecology",
    department: "OB-Gynecology",
    experience: "",
    rating: 0,
    education: "",
    bio: "OB-Gynecology specialist.",
    availability: "Schedule not available",
    image: "/doctors/doctor-280x281.png",
    gender: "female"
  },
  {
    id: 28,
    name: "Dr. Elchor Caralian",
    specialty: "Family Medicine",
    department: "Family Medicine",
    experience: "",
    rating: 0,
    education: "",
    bio: "Family Medicine specialist.",
    availability: "Schedule not available",
    image: "/doctors/1130796_OQ6UTW0-280x280.jpg",
    gender: "male"
  },
  {
    id: 29,
    name: "Dr. Lex Lycurgus Castillo",
    specialty: "Neurology",
    department: "Neurology",
    experience: "",
    rating: 0,
    education: "",
    bio: "Neurology specialist.",
    availability: "Tue, Fri: 9:00AM - 11:00AM",
    image: "/doctors/1130796_OQ6UTW0-280x280.jpg",
    gender: "male"
  },
  {
    id: 30,
    name: "Dr. Alih Bryan Catis",
    specialty: "General Surgery",
    department: "Surgery",
    experience: "",
    rating: 0,
    education: "",
    bio: "General Surgery specialist.",
    availability: "Tue, Thu: 4:00PM - 6:00PM | Sat: 8:00AM - 10:00AM",
    image: "/doctors/MG_0061-280x302.jpg",
    gender: "male"
  },
  {
    id: 31,
    name: "Dr. Marc Collao",
    specialty: "Pediatrics",
    department: "Pediatrics",
    experience: "",
    rating: 0,
    education: "",
    bio: "Pediatrics specialist.",
    availability: "Mon, Wed, Fri: 03:00PM - 05:00PM",
    image: "/doctors/unnamed-2-e1717140183195-280x270.jpg",
    gender: "male"
  },
  {
    id: 32,
    name: "Dr. Eva Marie Combe",
    specialty: "Anesthesiology",
    department: "Surgery",
    experience: "",
    rating: 0,
    education: "",
    bio: "Anesthesiology specialist.",
    availability: "Schedule not available",
    image: "/doctors/doctor-280x281.png",
    gender: "female"
  },
  {
    id: 33,
    name: "Dr. Reynaldo Combe",
    specialty: "Urology",
    department: "Surgery",
    experience: "",
    rating: 0,
    education: "",
    bio: "Urology specialist.",
    availability: "Fri: 8:00AM - 10:00AM",
    image: "/doctors/photo_2023-02-10_10-46-27-e1717140388113-280x250.jpg",
    gender: "male"
  },
  {
    id: 34,
    name: "Dr. Madelaine Cosing",
    specialty: "Nephrology",
    department: "Internal Medicine",
    experience: "",
    rating: 0,
    education: "",
    bio: "Nephrology specialist.",
    availability: "Schedule not available",
    image: "/doctors/doctor-280x281.png",
    gender: "female"
  },
  {
    id: 35,
    name: "Dr. Edgardo Cruz",
    specialty: "General Surgery",
    department: "Surgery",
    experience: "",
    rating: 0,
    education: "",
    bio: "General Surgery specialist.",
    availability: "Tue, Fri: 10:00AM - 12:00NN | Wed: 4:00PM - 6:00PM | Thu: 2:00PM - 5:00PM",
    image: "https://www.metrodocshospital.com/wp-content/uploads/2023/11/viber_image_2023-10-27_09-27-27-869-e1717139002112-280x280.jpg",
    gender: "male"
  },
  {
    id: 36,
    name: "Dr. Leila Cruz",
    specialty: "Pediatrics",
    department: "Pediatrics",
    experience: "",
    rating: 0,
    education: "",
    bio: "Pediatrics specialist.",
    availability: "Mon, Wed, Thu, Fri, Sat: 1:00-3:00PM | Tue: 9:00-11:00AM",
    image: "/doctors/IMG-2950-e1717140616298-280x256.jpg",
    gender: "female"
  },
  {
    id: 37,
    name: "Dr. Ritche Cruz",
    specialty: "Internal Medicine",
    department: "Internal Medicine",
    experience: "",
    rating: 0,
    education: "",
    bio: "Internal Medicine specialist.",
    availability: "Mon, Fri: 1:00-3:00PM",
    image: "/doctors/1130796_OQ6UTW0-280x280.jpg",
    gender: "male"
  },
  {
    id: 38,
    name: "Dr. Rhionne Dacalanio",
    specialty: "General Surgery",
    department: "Surgery",
    experience: "",
    rating: 0,
    education: "",
    bio: "General Surgery specialist.",
    availability: "Mon, Wed: 10:00AM - 12:00NN | Tue, Thu: 1:00PM - 3:00PM",
    image: "/doctors/1130796_OQ6UTW0-280x280.jpg",
    gender: "male"
  },
  {
    id: 39,
    name: "Dr. Cynthia Olivia De Leon",
    specialty: "OB-Gynecology",
    department: "OB-Gynecology",
    experience: "",
    rating: 0,
    education: "",
    bio: "OB-Gynecology specialist.",
    availability: "Schedule not available",
    image: "/doctors/doctor-280x281.png",
    gender: "female"
  },
  {
    id: 40,
    name: "Dr. Lara De Lumen",
    specialty: "Anesthesiology",
    department: "Surgery",
    experience: "",
    rating: 0,
    education: "",
    bio: "Anesthesiology specialist.",
    availability: "Schedule not available",
    image: "/doctors/doctor-280x281.png",
    gender: "female"
  },
  {
    id: 41,
    name: "Dr. Neil Andrew De Lumen",
    specialty: "Ophthalmology",
    department: "Ophthalmology",
    experience: "",
    rating: 0,
    education: "",
    bio: "Ophthalmology specialist.",
    availability: "Schedule not available",
    image: "/doctors/photo_2023-02-10_10-24-56-e1717140096859-280x264.jpg",
    gender: "male"
  },
  {
    id: 42,
    name: "Dr. Ditas Dela Cruz",
    specialty: "OB-Gynecology",
    department: "OB-Gynecology",
    experience: "",
    rating: 0,
    education: "",
    bio: "OB-Gynecology specialist.",
    availability: "Schedule not available",
    image: "/doctors/doctor-280x281.png",
    gender: "female"
  },
  {
    id: 43,
    name: "Dr. Artemio Jr. Dumo",
    specialty: "General Practice",
    department: "Family Medicine",
    experience: "",
    rating: 0,
    education: "",
    bio: "General Practice specialist.",
    availability: "Schedule not available",
    image: "/doctors/MG_0021-280x300.jpg",
    gender: "male"
  },
  {
    id: 44,
    name: "Dr. Angelito Duran",
    specialty: "Pediatrics",
    department: "Pediatrics",
    experience: "",
    rating: 0,
    education: "",
    bio: "Pediatrics specialist.",
    availability: "Schedule not available",
    image: "/doctors/photo_2023-02-10_10-00-00-duran-e1717140641838-280x253.jpg",
    gender: "male"
  },
  {
    id: 45,
    name: "Dr. Milagros Einanloo",
    specialty: "Gastroenterology",
    department: "Internal Medicine",
    experience: "",
    rating: 0,
    education: "",
    bio: "Gastroenterology specialist.",
    availability: "Schedule not available",
    image: "/doctors/doctor-280x281.png",
    gender: "female"
  },
  {
    id: 46,
    name: "Dr. Ana Lea Fernandez",
    specialty: "OB-Gynecology",
    department: "OB-Gynecology",
    experience: "",
    rating: 0,
    education: "",
    bio: "OB-Gynecology specialist.",
    availability: "Schedule not available",
    image: "/doctors/doctor-280x281.png",
    gender: "female"
  },
  {
    id: 47,
    name: "Dr. Elnora Salome Fortu",
    specialty: "Diabetology",
    department: "Internal Medicine",
    experience: "",
    rating: 0,
    education: "",
    bio: "Diabetology specialist.",
    availability: "Schedule not available",
    image: "/doctors/doctor-280x281.png",
    gender: "female"
  },
  {
    id: 48,
    name: "Dr. Bryan Leroy Francisco",
    specialty: "Anesthesiology",
    department: "Surgery",
    experience: "",
    rating: 0,
    education: "",
    bio: "Anesthesiology specialist.",
    availability: "Schedule not available",
    image: "/doctors/MG_0027-280x271.jpg",
    gender: "male"
  },
  {
    id: 49,
    name: "Dr. Ricardo Arcilla Francisco",
    specialty: "Nephrology",
    department: "Internal Medicine",
    experience: "",
    rating: 0,
    education: "",
    bio: "Nephrology specialist.",
    availability: "Wed, Sat: 4:00-6:00PM",
    image: "/doctors/1130796_OQ6UTW0-280x280.jpg",
    gender: "male"
  },
  {
    id: 50,
    name: "Dr. Shellygrace Fullante",
    specialty: "Rehabilitation Medicine",
    department: "Rehabilitation",
    experience: "",
    rating: 0,
    education: "",
    bio: "Rehabilitation Medicine specialist.",
    availability: "Wed: 2:00PM - 4:00PM",
    image: "/doctors/doctor-280x281.png",
    gender: "female"
  },
  {
    id: 51,
    name: "Dr. Gina Garcia",
    specialty: "Internal Medicine",
    department: "Internal Medicine",
    experience: "",
    rating: 0,
    education: "",
    bio: "Internal Medicine specialist.",
    availability: "Schedule not available",
    image: "/doctors/doctor-280x281.png",
    gender: "female"
  },
  {
    id: 52,
    name: "Dr. Noel Gaurano",
    specialty: "Pulmonology",
    department: "Internal Medicine",
    experience: "",
    rating: 0,
    education: "",
    bio: "Pulmonology specialist.",
    availability: "Mon, Tue, Wed, Thu, Fri, Sat, Sun: VIRTUAL CONSULTATION",
    image: "/doctors/photo_2023-02-10_11-18-42-e1717140848985-280x259.jpg",
    gender: "male"
  },
  {
    id: 53,
    name: "Dr. George Paul Habacon",
    specialty: "Pulmonology",
    department: "Internal Medicine",
    experience: "",
    rating: 0,
    education: "",
    bio: "Pulmonology specialist.",
    availability: "Fri: 1:00PM - 3:00PM",
    image: "/doctors/1130796_OQ6UTW0-280x280.jpg",
    gender: "male"
  },
  {
    id: 54,
    name: "Dr. Tristan Hilario",
    specialty: "Psychiatry",
    department: "Psychiatry",
    experience: "",
    rating: 0,
    education: "",
    bio: "Psychiatry specialist.",
    availability: "Schedule not available",
    image: "/doctors/1130796_OQ6UTW0-280x280.jpg",
    gender: "male"
  },
  {
    id: 55,
    name: "Dr. Geronimo Almario Jabson",
    specialty: "Neurosurgery",
    department: "Neurology",
    experience: "",
    rating: 0,
    education: "",
    bio: "Neurosurgery specialist.",
    availability: "Schedule not available",
    image: "/doctors/1130796_OQ6UTW0-280x280.jpg",
    gender: "male"
  },
  {
    id: 56,
    name: "Dr. Elena Borja Javier",
    specialty: "General Practice",
    department: "Family Medicine",
    experience: "",
    rating: 0,
    education: "",
    bio: "General Practice specialist.",
    availability: "Schedule not available",
    image: "/doctors/doctor-280x281.png",
    gender: "female"
  },
  {
    id: 57,
    name: "Dr. Julie Ann Jeciel",
    specialty: "Cardiology",
    department: "Cardiology",
    experience: "",
    rating: 0,
    education: "",
    bio: "Cardiology specialist.",
    availability: "Schedule not available",
    image: "/doctors/doctor-280x281.png",
    gender: "female"
  },
  {
    id: 58,
    name: "Dr. Anna Marie Lafiguera",
    specialty: "OB-Gynecology",
    department: "OB-Gynecology",
    experience: "",
    rating: 0,
    education: "",
    bio: "OB-Gynecology specialist.",
    availability: "Wed, Sat: 10:00AM - 12:00NN | Thu: 2:00PM - 4:00PM",
    image: "/doctors/doctor-280x281.png",
    gender: "female"
  },
  {
    id: 59,
    name: "Dr. Jimmy Lim",
    specialty: "General Surgery",
    department: "Surgery",
    experience: "",
    rating: 0,
    education: "",
    bio: "General Surgery specialist.",
    availability: "Mon, Wed, Fri: 1:00PM - 3:00PM",
    image: "/doctors/viber_image_2023-03-31_09-35-21-561-280x280.jpg",
    gender: "male"
  },
  {
    id: 60,
    name: "Dr. Narcelita Lim",
    specialty: "Pulmonology",
    department: "Internal Medicine",
    experience: "",
    rating: 0,
    education: "",
    bio: "Pulmonology specialist.",
    availability: "Mon, Thu: 9:00AM - 12:00NN",
    image: "/doctors/doctor-280x281.png",
    gender: "female"
  },
  {
    id: 61,
    name: "Dr. Enrique Ian Lorenzo",
    specialty: "Urology",
    department: "Surgery",
    experience: "",
    rating: 0,
    education: "",
    bio: "Urology specialist.",
    availability: "Wed: 3:00PM - 5:00PM",
    image: "/doctors/1130796_OQ6UTW0-280x280.jpg",
    gender: "male"
  },
  {
    id: 62,
    name: "Dr. Ma. Teresa Magtibay",
    specialty: "Pulmonology",
    department: "Internal Medicine",
    experience: "",
    rating: 0,
    education: "",
    bio: "Pulmonology specialist.",
    availability: "Schedule not available",
    image: "/doctors/doctor-280x281.png",
    gender: "female"
  },
  {
    id: 63,
    name: "Dr. Ma. Luisa Malijan",
    specialty: "Family Medicine",
    department: "Family Medicine",
    experience: "",
    rating: 0,
    education: "",
    bio: "Family Medicine specialist.",
    availability: "Schedule not available",
    image: "/doctors/photo_2023-02-10_10-53-46-e1717139776877-280x275.jpg",
    gender: "female"
  },
  {
    id: 64,
    name: "Dr. Jordel Maravilla",
    specialty: "Family Medicine",
    department: "Family Medicine",
    experience: "",
    rating: 0,
    education: "",
    bio: "Family Medicine specialist.",
    availability: "Schedule not available",
    image: "/doctors/1130796_OQ6UTW0-280x280.jpg",
    gender: "male"
  },
  {
    id: 65,
    name: "Dr. Felipe Martinez",
    specialty: "Family Medicine",
    department: "Family Medicine",
    experience: "",
    rating: 0,
    education: "",
    bio: "Family Medicine specialist.",
    availability: "Schedule not available",
    image: "/doctors/1130796_OQ6UTW0-280x280.jpg",
    gender: "male"
  },
  {
    id: 66,
    name: "Dr. Elmer John Medina",
    specialty: "Anesthesiology",
    department: "Surgery",
    experience: "",
    rating: 0,
    education: "",
    bio: "Anesthesiology specialist.",
    availability: "Schedule not available",
    image: "/doctors/MG_0138-280x295.jpg",
    gender: "male"
  },
  {
    id: 67,
    name: "Dr. John Victor",
    specialty: "Rehabilitation Medicine",
    department: "Rehabilitation",
    experience: "",
    rating: 0,
    education: "",
    bio: "Rehabilitation Medicine specialist.",
    availability: "Tue, Thu: 2:00PM - 4:00PM",
    image: "/doctors/1130796_OQ6UTW0-280x280.jpg",
    gender: "male"
  },
  {
    id: 68,
    name: "Dr. Lawrence Manalili",
    specialty: "Rehabilitation Medicine",
    department: "Rehabilitation",
    experience: "",
    rating: 0,
    education: "",
    bio: "Rehabilitation Medicine specialist.",
    availability: "Sat: 10:00AM - 12:00NN",
    image: "/doctors/1130796_OQ6UTW0-280x280.jpg",
    gender: "male"
  },
  {
    id: 69,
    name: "Dr. Eduardo Austria",
    specialty: "Rehabilitation Medicine",
    department: "Rehabilitation",
    experience: "",
    rating: 0,
    education: "",
    bio: "Rehabilitation Medicine specialist.",
    availability: "Fri: 9:00AM - 12:00NN",
    image: "/doctors/1130796_OQ6UTW0-280x280.jpg",
    gender: "male"
  },
  {
    id: 70,
    name: "Dr. Jason Paul Medina",
    specialty: "Nephrology",
    department: "Internal Medicine",
    experience: "",
    rating: 0,
    education: "",
    bio: "Nephrology specialist.",
    availability: "Mon: 1:00PM - 3:00PM",
    image: "/doctors/1130796_OQ6UTW0-280x280.jpg",
    gender: "male"
  },
  {
    id: 71,
    name: "Dr. Maria Scarlett Medina",
    specialty: "OB-Gynecology",
    department: "OB-Gynecology",
    experience: "",
    rating: 0,
    education: "",
    bio: "OB-Gynecology specialist.",
    availability: "Mon: 1:00PM - 3:00PM | Wed: 8:00AM - 10:00AM",
    image: "/doctors/unnamed-1-e1717140583720-280x280.jpg",
    gender: "female"
  },
  {
    id: 72,
    name: "Dr. Diane Marie Mendoza",
    specialty: "Internal Medicine",
    department: "Internal Medicine",
    experience: "",
    rating: 0,
    education: "",
    bio: "Internal Medicine specialist.",
    availability: "Mon: 12:00-3:00PM | Sat: 12:00-2:00PM",
    image: "/doctors/doctor-280x281.png",
    gender: "female"
  },
  {
    id: 73,
    name: "Dr. Flida Mendoza",
    specialty: "OB-Gynecology",
    department: "OB-Gynecology",
    experience: "",
    rating: 0,
    education: "",
    bio: "OB-Gynecology specialist.",
    availability: "Schedule not available",
    image: "/doctors/doctor-280x281.png",
    gender: "female"
  },
  {
    id: 74,
    name: "Dr. Marivic Mercadal",
    specialty: "OB-Gynecology",
    department: "OB-Gynecology",
    experience: "",
    rating: 0,
    education: "",
    bio: "OB-Gynecology specialist.",
    availability: "Schedule not available",
    image: "/doctors/doctor-280x281.png",
    gender: "female"
  },
  {
    id: 75,
    name: "Dr. Carina Ursula Miranda",
    specialty: "Anesthesiology",
    department: "Surgery",
    experience: "",
    rating: 0,
    education: "",
    bio: "Anesthesiology specialist.",
    availability: "Schedule not available",
    image: "/doctors/doctor-280x281.png",
    gender: "female"
  },
  {
    id: 76,
    name: "Dr. Harold Nanquil",
    specialty: "General Surgery",
    department: "Surgery",
    experience: "",
    rating: 0,
    education: "",
    bio: "General Surgery specialist.",
    availability: "Mon, Wed, Fri: 4:00PM - 6:00PM",
    image: "/doctors/1130796_OQ6UTW0-280x280.jpg",
    gender: "male"
  },
  {
    id: 77,
    name: "Dr. Joy Natividad",
    specialty: "OB-Gynecology",
    department: "OB-Gynecology",
    experience: "",
    rating: 0,
    education: "",
    bio: "OB-Gynecology specialist.",
    availability: "Tue, Sat: 9:00AM - 11:00AM",
    image: "/doctors/doctor-280x281.png",
    gender: "female"
  },
  {
    id: 78,
    name: "Dr. Dennis Naval",
    specialty: "Neurology",
    department: "Neurology",
    experience: "",
    rating: 0,
    education: "",
    bio: "Neurology specialist.",
    availability: "Wed, Sat: 3:00PM - 5:00PM",
    image: "/doctors/MG_0056-280x242.jpg",
    gender: "male"
  },
  {
    id: 79,
    name: "Dr. Wilfredo Navoa",
    specialty: "Radiology",
    department: "Radiology",
    experience: "",
    rating: 0,
    education: "",
    bio: "Radiology specialist.",
    availability: "Wed, Sat: 3:00-5:00PM",
    image: "/doctors/doctor-280x281.png",
    gender: "male"
  },
  {
    id: 80,
    name: "Dr. Leonora Obmasca",
    specialty: "Internal Medicine",
    department: "Internal Medicine",
    experience: "",
    rating: 0,
    education: "",
    bio: "Internal Medicine specialist.",
    availability: "Mon: 4:00-6:00PM | Wed, Fri: 10:00-12:00PM",
    image: "/doctors/doctor-280x281.png",
    gender: "female"
  },
  {
    id: 81,
    name: "Dr. Emerson Oliver",
    specialty: "Radiology",
    department: "Radiology",
    experience: "",
    rating: 0,
    education: "",
    bio: "Radiology specialist.",
    availability: "Schedule not available",
    image: "/doctors/1130796_OQ6UTW0-280x280.jpg",
    gender: "male"
  },
  {
    id: 82,
    name: "Dr. Jamie Rose Orlina",
    specialty: "Pediatrics",
    department: "Pediatrics",
    experience: "",
    rating: 0,
    education: "",
    bio: "Pediatrics specialist.",
    availability: "Sat: 9:00-11:00AM",
    image: "/doctors/doctor-280x281.png",
    gender: "female"
  },
  {
    id: 83,
    name: "Dr. Yolanda Orlina",
    specialty: "Nephrology",
    department: "Internal Medicine",
    experience: "",
    rating: 0,
    education: "",
    bio: "Nephrology specialist.",
    availability: "Mon, Wed, Fri: 4:00PM - 6:00PM",
    image: "/doctors/photo_2023-02-10_11-25-42-2-e1717140790537-280x251.jpg",
    gender: "female"
  },
  {
    id: 84,
    name: "Dr. Gerlie Ortiz",
    specialty: "Cardiology",
    department: "Cardiology",
    experience: "",
    rating: 0,
    education: "",
    bio: "Cardiology specialist.",
    availability: "Tue: 3:00PM - 4:00PM",
    image: "/doctors/doctor-280x281.png",
    gender: "female"
  },
  {
    id: 85,
    name: "Dr. Gladys Ann Pabrua",
    specialty: "OB-Gynecology",
    department: "OB-Gynecology",
    experience: "",
    rating: 0,
    education: "",
    bio: "OB-Gynecology specialist.",
    availability: "Tue, Thu: 1:00-2:00PM",
    image: "/doctors/doctor-280x281.png",
    gender: "female"
  },
  {
    id: 86,
    name: "Dr. Percival Pangilinan",
    specialty: "Orthopedic Surgery",
    department: "Rehabilitation",
    experience: "",
    rating: 0,
    education: "",
    bio: "Orthopedic Surgery specialist.",
    availability: "Mon, Wed: 1:00PM - 2:00PM",
    image: "/doctors/1130796_OQ6UTW0-280x280.jpg",
    gender: "male"
  },
  {
    id: 87,
    name: "Dr. Sharmaine Pangilinan",
    specialty: "Anesthesiology",
    department: "Surgery",
    experience: "",
    rating: 0,
    education: "",
    bio: "Anesthesiology specialist.",
    availability: "Schedule not available",
    image: "/doctors/doctor-280x281.png",
    gender: "female"
  },
  {
    id: 88,
    name: "Dr. Rocco Carmine Paragas",
    specialty: "General Surgery",
    department: "Surgery",
    experience: "",
    rating: 0,
    education: "",
    bio: "General Surgery specialist.",
    availability: "Mon, Wed: 1:00PM - 3:00PM",
    image: "/doctors/1130796_OQ6UTW0-280x280.jpg",
    gender: "male"
  },
  {
    id: 89,
    name: "Dr. Adelina Paule",
    specialty: "Cardiology",
    department: "Cardiology",
    experience: "",
    rating: 0,
    education: "",
    bio: "Cardiology specialist.",
    availability: "Tue, Thu, Sat: 9:00AM - 11:00AM",
    image: "/doctors/doctor-280x281.png",
    gender: "female"
  },
  {
    id: 90,
    name: "Dr. May Angela Pelayo",
    specialty: "Infectious Disease",
    department: "Internal Medicine",
    experience: "",
    rating: 0,
    education: "",
    bio: "Infectious Disease specialist.",
    availability: "Schedule not available",
    image: "/doctors/doctor-280x281.png",
    gender: "female"
  },
  {
    id: 91,
    name: "Dr. Khristine Girado Pizarro",
    specialty: "ENT",
    department: "ENT",
    experience: "",
    rating: 0,
    education: "",
    bio: "ENT specialist.",
    availability: "Mon, Thu: 09:00AM - 11:00AM",
    image: "/doctors/photo_2023-02-22_11-26-53-e1717140686349-280x281.jpg",
    gender: "female"
  },
  {
    id: 92,
    name: "Dr. Juvenal Quitiquit",
    specialty: "General Surgery",
    department: "Surgery",
    experience: "",
    rating: 0,
    education: "",
    bio: "General Surgery specialist.",
    availability: "Schedule not available",
    image: "/doctors/1130796_OQ6UTW0-280x280.jpg",
    gender: "male"
  },
  {
    id: 93,
    name: "Dr. Roger Quitiquit",
    specialty: "Orthopedic Surgery",
    department: "Rehabilitation",
    experience: "",
    rating: 0,
    education: "",
    bio: "Orthopedic Surgery specialist.",
    availability: "Thu: 11:00AM - 12:00NN",
    image: "/doctors/1130796_OQ6UTW0-280x280.jpg",
    gender: "male"
  },
  {
    id: 94,
    name: "Dr. Donard Quitaleg",
    specialty: "Radiology",
    department: "Radiology",
    experience: "",
    rating: 0,
    education: "",
    bio: "Radiology specialist.",
    availability: "Schedule not available",
    image: "/doctors/1130796_OQ6UTW0-280x280.jpg",
    gender: "male"
  },
  {
    id: 95,
    name: "Dr. Rico Rayos Del Sol",
    specialty: "General Surgery",
    department: "Surgery",
    experience: "",
    rating: 0,
    education: "",
    bio: "General Surgery specialist.",
    availability: "Schedule not available",
    image: "/doctors/1130796_OQ6UTW0-280x280.jpg",
    gender: "male"
  },
  {
    id: 96,
    name: "Dr. Renante Remigio",
    specialty: "Internal Medicine",
    department: "Internal Medicine",
    experience: "",
    rating: 0,
    education: "",
    bio: "Internal Medicine specialist.",
    availability: "Sat: 10:00AM-12:00PM",
    image: "/doctors/1130796_OQ6UTW0-280x280.jpg",
    gender: "male"
  },
  {
    id: 97,
    name: "Dr. Romelia Sabarre",
    specialty: "Pediatrics",
    department: "Pediatrics",
    experience: "",
    rating: 0,
    education: "",
    bio: "Pediatrics specialist.",
    availability: "Schedule not available",
    image: "/doctors/doctor-280x281.png",
    gender: "female"
  },
  {
    id: 98,
    name: "Dr. Francisco Jr. San Diego",
    specialty: "Internal Medicine",
    department: "Internal Medicine",
    experience: "",
    rating: 0,
    education: "",
    bio: "Internal Medicine specialist.",
    availability: "Schedule not available",
    image: "/doctors/photo_2023-02-10_11-25-42-3-e1717139895177-280x231.jpg",
    gender: "male"
  },
  {
    id: 99,
    name: "Dr. Julie Ann San Diego",
    specialty: "OB-Gynecology",
    department: "OB-Gynecology",
    experience: "",
    rating: 0,
    education: "",
    bio: "OB-Gynecology specialist.",
    availability: "Mon: 3:00PM-5:00PM | Wed: 8:00AM-10:00AM",
    image: "/doctors/doctor-280x281.png",
    gender: "female"
  },
  {
    id: 100,
    name: "Dr. Celesa Santos",
    specialty: "Radiology",
    department: "Radiology",
    experience: "",
    rating: 0,
    education: "",
    bio: "Radiology specialist.",
    availability: "Mon: 3:00PM-5:00PM",
    image: "/doctors/thumbnail-e1717139571311-280x271.jpg",
    gender: "female"
  },
  {
    id: 101,
    name: "Dr. Rodrigo Santos",
    specialty: "Cardiology",
    department: "Cardiology",
    experience: "",
    rating: 0,
    education: "",
    bio: "Cardiology specialist.",
    availability: "Schedule not available",
    image: "/doctors/1130796_OQ6UTW0-280x280.jpg",
    gender: "male"
  },
  {
    id: 102,
    name: "Dr. Ma. Liza Sarenas",
    specialty: "Ophthalmology",
    department: "Ophthalmology",
    experience: "",
    rating: 0,
    education: "",
    bio: "Ophthalmology specialist.",
    availability: "Schedule not available",
    image: "/doctors/doctor-280x281.png",
    gender: "female"
  },
  {
    id: 103,
    name: "Dr. Cesar Soriano",
    specialty: "Anesthesiology",
    department: "Surgery",
    experience: "",
    rating: 0,
    education: "",
    bio: "Anesthesiology specialist.",
    availability: "Schedule not available",
    image: "/doctors/1130796_OQ6UTW0-280x280.jpg",
    gender: "male"
  },
  {
    id: 104,
    name: "Dr. Jesse Soriano",
    specialty: "OB-Gynecology",
    department: "OB-Gynecology",
    experience: "",
    rating: 0,
    education: "",
    bio: "OB-Gynecology specialist.",
    availability: "Tue: 12:00NN - 2:00PM | Wed: 3:00PM - 5:00PM",
    image: "/doctors/1130796_OQ6UTW0-280x280.jpg",
    gender: "male"
  },
  {
    id: 105,
    name: "Dr. Ryan Tipon",
    specialty: "Internal Medicine",
    department: "Internal Medicine",
    experience: "",
    rating: 0,
    education: "",
    bio: "Internal Medicine specialist.",
    availability: "Tue: 1:00-3:00PM",
    image: "/doctors/image_6487327-e1717140884401-280x282.jpg",
    gender: "male"
  },
  {
    id: 106,
    name: "Dr. Cecilia Milagros Tobillo",
    specialty: "Pediatrics",
    department: "Pediatrics",
    experience: "",
    rating: 0,
    education: "",
    bio: "Pediatrics specialist.",
    availability: "Tue, Thu: 2:00-4:00PM | Sat: 10:00-12:00PM",
    image: "/doctors/photo_2023-02-10_11-25-42-e1717140939478-280x266.jpg",
    gender: "female"
  },
  {
    id: 107,
    name: "Dr. Selma Valderama",
    specialty: "Pediatrics",
    department: "Pediatrics",
    experience: "",
    rating: 0,
    education: "",
    bio: "Pediatrics specialist.",
    availability: "Schedule not available",
    image: "/doctors/MG_0101-scaled-e1717139496394-280x284.jpg",
    gender: "female"
  },
  {
    id: 108,
    name: "Dr. Madonna Valdez",
    specialty: "Pediatrics",
    department: "Pediatrics",
    experience: "",
    rating: 0,
    education: "",
    bio: "Pediatrics specialist.",
    availability: "Schedule not available",
    image: "/doctors/doctor-280x281.png",
    gender: "female"
  },
  {
    id: 109,
    name: "Dr. Julie Ann Valencia",
    specialty: "OB-Gynecology",
    department: "OB-Gynecology",
    experience: "",
    rating: 0,
    education: "",
    bio: "OB-Gynecology specialist.",
    availability: "Schedule not available",
    image: "/doctors/doctor-280x281.png",
    gender: "female"
  },
  {
    id: 110,
    name: "Dr. Josephine Elaine Vargas",
    specialty: "Anesthesiology",
    department: "Surgery",
    experience: "",
    rating: 0,
    education: "",
    bio: "Anesthesiology specialist.",
    availability: "Schedule not available",
    image: "/doctors/photo_2023-02-10_10-10-39-varagas-e1717139429103-280x265.jpg",
    gender: "female"
  },
  {
    id: 111,
    name: "Dr. Joseph Villafuerte",
    specialty: "Dentistry",
    department: "Dentistry",
    experience: "",
    rating: 0,
    education: "",
    bio: "Dentistry specialist.",
    availability: "Schedule not available",
    image: "/doctors/1130796_OQ6UTW0-280x280.jpg",
    gender: "male"
  },
  {
    id: 112,
    name: "Dr. Cristina Villanueva",
    specialty: "Pediatrics",
    department: "Pediatrics",
    experience: "",
    rating: 0,
    education: "",
    bio: "Pediatrics specialist.",
    availability: "Schedule not available",
    image: "/doctors/doctor-280x281.png",
    gender: "female"
  },
  {
    id: 113,
    name: "Dr. Arleen Yunzal",
    specialty: "Family Medicine",
    department: "Family Medicine",
    experience: "",
    rating: 0,
    education: "",
    bio: "Family Medicine specialist.",
    availability: "Schedule not available",
    image: "/doctors/doctor-280x281.png",
    gender: "female"
  },
  {
    id: 114,
    name: "Dr. Michelle Zapanta",
    specialty: "Pediatrics",
    department: "Pediatrics",
    experience: "",
    rating: 0,
    education: "",
    bio: "Pediatrics specialist.",
    availability: "Schedule not available",
    image: "/doctors/MG_0098-280x280.jpg",
    gender: "female"
  },
];
export function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-");
}
export const doctors: Doctor[] = rawDoctorsData.map((doc) => ({
  ...doc,
  slug: slugify(doc.name), // This injects the missing property
}));

export const getDoctorBySlug = (slug: string) => {
  return doctors.find((d) => d.slug === slug);
};

export const getDoctors = () => doctors;

export function getDoctorById(id: number | string): Doctor | undefined {
  const n = typeof id === "string" ? parseInt(id, 10) : id;
  return doctors.find((d) => d.id === n);
}

export const DOCTOR_DEPARTMENT_FILTERS = [
  "All",
  "Cardiology",
  "Dentistry",
  "Dermatology",
  "Emergency",
  "ENT",
  "Family Medicine",
  "Internal Medicine",
  "Laboratory",
  "Neurology",
  "OB-Gynecology",
  "Oncology",
  "Ophthalmology",
  "Pediatrics",
  "Psychiatry",
  "Radiology",
  "Rehabilitation",
  "Surgery",
] as const;

export function getDoctorDepartmentFilters(): string[] {
  return [...DOCTOR_DEPARTMENT_FILTERS];
}
